### ISSUE TITLE
'sh' filetype should use the built-in :Man command

### ISSUE THREAD

**Issue by justinmk** [Keithbsmiley/investigate.vim#13]
see https://news.ycombinator.com/item?id=8799509

```vim
:runtime ftplugin/man.vim
:Man ls
```

**Comment by Keithbsmiley** [comment]
I use this, I'd love this, but I'm not sure I want to force the runtime source on users.

This would be an easy setting to setup though:

```vim
let g:investigate_custom_for_sh="^i:Man ^s"
```

Where `^i` tells investigate not to run it through `open` (on OS X) and `^s` gets replaced with the `<cword>`

**Comment by jalcine** [comment]
Maybe have this an option to switch to use the internal `:Man` command?

**Comment by Keithbsmiley** [comment]
Well I would say setting the option above is the best way to do that?

**Comment by jalcine** [comment]
Touche!

**Comment by Keithbsmiley** [comment]
Closing recommending use of the above setting!

**Comment by jalcine** [comment]
@Keithbsmiley going to beat the horse back to life (hopefully not, haha) but why not make this the default setting?

**Comment by Keithbsmiley** [comment]
See above.


--
Keith Smiley

**Comment by jalcine** [comment]
I know, hence my comment. Why not consider it a default setting?

**Comment by Keithbsmiley** [comment]
> I'm not sure I want to force the runtime source on users.

**Comment by jalcine** [comment]
Noted, didn't see that. Thanks, nonetheless!
