### ISSUE TITLE
Add support for single lookup URL (like devdocs.io)

### ISSUE THREAD

**Issue by yacoob** [Keithbsmiley/investigate.vim#14]
It'd be nice to add a way for configuring a single lookup URL for all filetypes, without having to define a ton of `investigate_url_for_foo` variables. I usually use devdocs.io, which is able to search through multiple docsets and very convenient as it also works offline. It's a bit like Dash, but doesn't require a separate app :)

**Comment by Keithbsmiley** [comment]
This looks like a great resource! Can you isolate a URL for the query. So that I could do something like `http://devdocs.io/?q=foo` to search for `foo`?

**Comment by Keithbsmiley** [comment]
Nevermind! this happens to be `devdocs.io/#q=foo` (from http://devdocs.io/help)

**Comment by Keithbsmiley** [comment]
Please test the branch in https://github.com/Keithbsmiley/investigate.vim/pull/15 with the commented URL string.

**Comment by yacoob** [comment]
The problem is, the query should ideally contain the name of the doctest to search through, to narrow down the list of results (eg. "js date" from devdocs help page). We can use the `ftype` for this, but I'm betting there are discrepancies between vim's `ftype` string and devdocs' docset name :(

**Comment by Keithbsmiley** [comment]
Hmm, yea. At that point this is getting too custom and even though they'd have the same base URL you'd need to specify them. If the filetypes were the same I could add an identifier for that in the substitute command, but that wouldn't solve the problem it sounds like.

**Comment by Keithbsmiley** [comment]
Closing this since having to change any part of the string for different languages means you should probably just use the language specific URLs. If you wanted to you write your own function that converts between the different filename identifiers for vim vs the site.
